### ISSUE TITLE
Add reconnect method

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#302]
### 📝 Description of the feature

launch_session(RPC_SERVER, 50051) when server is running throw error 
![image](https://github.com/ansys/pyedb-core/assets/74993647/aba9529f-4f6b-41e8-a612-a0bae7623b18)

**Comment by hiro727** [comment]
`attach_session` does connect to existing server. was a user error as launch_session was being called without closing the first one
