### ISSUE TITLE
use_q3d_for_dc missing 

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#306]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I can't find the flag use_q3d_for_dc missing  in the api.
this is very important.

equivalent to this 
![image](https://github.com/ansys/pyedb-core/assets/74993647/ae93a167-c990-4d5b-805a-40b01aef19a3)

### 📝 Steps to reproduce

I can't find the flag use_q3d_for_dc missing  in the api.

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pyedb-core
```

**Comment by drewm102** [comment]
Closed by #378
