### ISSUE TITLE
enforce_causality missing to SweepData

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#307]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

flag enforce_causility missing to SweepData

### 📝 Steps to reproduce

flag enforce_causility missing to SweepData

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pyedb-core
```

**Comment by drewm102** [comment]
Closed by #378
