### ISSUE TITLE
enforce_passivity missing to SweepData

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#308]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

flag missing

### 📝 Steps to reproduce

flag missing

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pyedb-core
```

**Comment by drewm102** [comment]
Closed by #378
