### ISSUE TITLE
MeshSizeFactor missing

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#310]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

MeshSizeFactor missing in Initial mesh settings

### 📝 Steps to reproduce

MeshSizeFactor missing in Initial mesh settings

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pyedb-core
```

**Comment by drewm102** [comment]
Closed by #378
