### ISSUE TITLE
Circular import error when importing terminal

### ISSUE THREAD

**Issue by SMoraisAnsys** [ansys/pyedb-core#312]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I just installed pyedb-core and wanted to look at the tests (good job on that part btw).

When paying with "mock/test_terminals.py" I ended up catching a circular import with the simple command `from ansys.edb.core import terminal`. The current test file seem to work because of side effects related to importing `from utils.fixtures import * `. before `from ansys.edb.core import terminal`.

### 📝 Steps to reproduce

Launch from anywhere to see the error

python -c "from ansys.edb.core import terminal"

Launch from the project (to be able to call the second import) to see the side effect

python -c "from tests.mock.utils.fixtures import *; from ansys.edb.core import terminal"

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023.R2 but not relevant for this problem

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
Not relevant
```

**Comment by chenchienjacklin** [comment]
@drewm102 This issue should already be resolved in this PR. https://github.com/ansys/pyedb-core/commit/2cabcff0741aab7b4bd2f2aa20cfdb48cd1c7d78
