### ISSUE TITLE
UseShellElements missing ? 

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#319]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

![image](https://github.com/ansys/pyedb-core/assets/74993647/38317ce8-ba55-4356-a9cf-43f4ea3d5900)

### 📝 Steps to reproduce

![image](https://github.com/ansys/pyedb-core/assets/74993647/53ece8e4-14a7-4a66-947a-d9b65d98a82e)

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pyedb-core
```

**Comment by drewm102** [comment]
Closed by #378
