### ISSUE TITLE
AutoSMatOnlySolve missing ? 

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#320]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I didn't find the equiavalent in HfssSimulationSetup

![image](https://github.com/ansys/pyedb-core/assets/74993647/8c49d65f-5559-4b3f-a750-d389b48fab35)

### 📝 Steps to reproduce

![image](https://github.com/ansys/pyedb-core/assets/74993647/019542e5-7203-4d2e-86ca-517fda6d74f9)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

not relevant

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pyedb-core
```

**Comment by drewm102** [comment]
Closed by #378
