### ISSUE TITLE
didn't found passivity and causality enforcement which are in SweepData in .NET api.

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#321]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

fearture missing

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pyedb-core
```

**Comment by drewm102** [comment]
#378
