### ISSUE TITLE
MeshOperation question

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#323]
### Description of the modifications

https://edb.docs.pyansys.com/version/dev/api/_autosummary/ansys.edb.simulation_setup.MeshOperation.net_layer_info.html#ansys.edb.simulation_setup.MeshOperation.net_layer_info

The third argument (bool) is it to enable meshop or really sheet ?

**Comment by drewm102** [comment]
@svandenb-dev It is for setting if the net/layer combo is a sheet
