### ISSUE TITLE
Missing HealingOption ? 

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#324]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

![image](https://github.com/ansys/pyedb-core/assets/74993647/2d8a937b-5707-4ecf-980e-3bbc081b349f)

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pyedb-core
```

**Comment by drewm102** [comment]
Closed by #378
