### ISSUE TITLE
Navigation pane for API reference section is not formatted correctly

### ISSUE THREAD

**Issue by PipKat** [ansys/pyedb-core#339]
### Description of the modifications

The right navigation pane is not listing the modules vertically. Instead it lists three across each line as shown in the following figure. Also, when trying to check the PY files against the rendered doc, it was hard to locate modules in this navigation pane because they were not alphabetical (which is standard). However, newer repos are using external [Sphinx AutoAPI](https://pypi.org/project/sphinx-autoapi/) extension to generate API reference documentation rather than the native (built-in) sphinx.ext.autodoc extension The Sphinx AutoAPI extension finds and generates content by parsing the source code rather than manually having to build the API doc sections like you have done. I'm tagging @SMoraisAnsys and @RobPasMue for feedback.

![image](https://github.com/ansys/pyedb-core/assets/84872299/8a88c63c-c9de-48d9-b487-38ab883b478d)

**Comment by drewm102** [comment]
@SMoraisAnsys It looks like this is resolved based on the current documentation here:

https://edb.core.docs.pyansys.com/version/stable/api/index.html

can we close this out? Thanks!

**Comment by RobPasMue** [comment]
Closing!
