### ISSUE TITLE
PadstackInstanceTerminal.create() docstring wrong

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#373]
### Description of the modifications

pyedb code:

    def create(self, padstack_instance, name=None, layer=None, is_ref=False):
        """Create an edge terminal.

        Parameters
        ----------
        prim_id : int
            Primitive ID.
        point_on_edge : list
            Coordinate of the point to define the edge terminal.
            The point must be on the target edge but not on the two
            ends of the edge.
        terminal_name : str, optional
            Name of the terminal. The default is ``None``, in which case the
            default name is assigned.
        is_ref : bool, optional
            Whether it is a reference terminal. The default is ``False``.
        Returns
        -------
        Edb.Cell.Terminal.EdgeTerminal

online doc

![image](https://github.com/ansys/pyedb-core/assets/74993647/b635d50c-5e6a-4376-b6f5-c1bdbd056bdd)

**Comment by hiro727** [comment]
@svandenb-dev your pyedb code shows `EdgeTerminal` whereas the doc shows `PadstackInstanceTerminal`.
doc for each method seems correct. can you clarify?

**Comment by svandenb-dev** [comment]
@hiro727 I will check again maybe this was a mistake

**Comment by drewm102** [comment]
@svandenb-dev It looks like the docstring is correct. I'm going to close this out for now
