### ISSUE TITLE
PolygonData.CreateFromBBox() missing

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#374]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

This method available in .NET is not implemented in gRPC.

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
NA
```

**Comment by hiro727** [comment]
@svandenb-dev it's part of a constructor now. try passing it as
```py
ll = (0,0)
ur = (1e-6, 1e-6)
PolygonData(lower_left=ll, upper_right=ur)
```
