### ISSUE TITLE
PadstackDefData.GetConnectionPt() API is missing

### ISSUE THREAD

**Issue by drewm102** [ansys/pyedb-core#375]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The PadstackDefData.GetConnectionPt() API is missing

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

24.2

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
NA
```

**Comment by hiro727** [comment]
@drewm102 I don't see this is available in dotnet either, maybe an enhancement?
