### ISSUE TITLE
2024.2 abd dev main branch grive error while attaching session

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#377]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I have one EDB already open when I try to attach the session before opening a second EDB I got this error:
![image](https://github.com/ansys/pyedb-core/assets/74993647/5bc417c3-aac9-4179-9010-57f5d84a82c0)
Seems the attach command is trying to start a new session according to the log

### 📝 Steps to reproduce

load 2 EDB files

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
NA
```

**Comment by hiro727** [comment]
error is expected. instead of opening multiple EDBs under multiple sessions, open them in a single session
