### ISSUE TITLE
BUG: Path class doesn't expose the property polygon_data

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#382]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

There is no polygon_data available from Net class (which is available with .NET api). I also didn't find anything in the documentation.

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
NA
```

**Comment by hiro727** [comment]
same issue as #301 

The fix was added a while ago but seems to be lost during repo migrations, will apply the same change here
