### ISSUE TITLE
BUG: EdgeTerminal.product_solver_names(database.ProductIdType.HFSS_3D_LAYOUT) failing

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#383]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

![image](https://github.com/ansys/pyedb-core/assets/74993647/b0537803-0c96-481c-b7ae-5809257062da)

![image](https://github.com/ansys/pyedb-core/assets/74993647/2ca86148-1d2d-4a84-99c0-0649167da428)

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
NA
```

**Comment by hiro727** [comment]
missing conversion from enum to underlying int
