### ISSUE TITLE
PadstackInstance.component getter return broken component object

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#384]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

![image](https://github.com/ansys/pyedb-core/assets/74993647/ed7d05f1-5d25-4124-8e5b-4b31189dc846)

![image](https://github.com/ansys/pyedb-core/assets/74993647/5cbbdf1e-a504-4798-981f-d54627316933)

![image](https://github.com/ansys/pyedb-core/assets/74993647/8a155a2a-dd3a-4587-a7c5-bf1333dd1c4c)

I checked the pin has net and all looks ok.

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
NA
```

**Comment by hiro727** [comment]
`ConnObj.component` method is incorrectly returning `ComponentGroup` instead of `Component`

**Comment by drewm102** [comment]
@svandenb-dev Is the pin in question part of a component? If not, the behavior you are seeing is expected since the ComponentGroup returned by the component property is null and therefore throws an exception when a method is called on it

**Comment by svandenb-dev** [comment]
We can close issue. This was open long time ago.
