### ISSUE TITLE
changing Hfss simulation AdaptType doesn't not preserve the setup name

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#387]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When we change HFSS simulation type to Single frequency, multi freuqnecy or brandband, the grpc EBD api removes the setup name with replacing as an empty string.

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

NA

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
NA
```

**Comment by drewm102** [comment]
@svandenb-dev This fix required a server side change and should now be fixed in the R24.2 install
