### ISSUE TITLE
BUG: PadstackInstanceTerminal.padstack_instance property fails

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#429]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When a Padstackinstance is defined and we use the delete() method. the PadstackInstance is also removed. Therefore I tried the cast the PadstackInstance from PadstackinstanceTerminal to instantiate a new Padstackinstance but it fails. 

I am not sure if this is a bug from PadstackInstanceTerminal.delete() Are we supposed to loose the PadstackInstance too ?

![image](https://github.com/user-attachments/assets/836f6978-838b-4e85-ae63-2612fe209adb)

![image](https://github.com/user-attachments/assets/9ad2ceca-009c-458a-bf30-1c5da80982a6)

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
Na
```

**Comment by drewm102** [comment]
@svandenb-dev From my testing, deleting a PadstackInstanceTerminal does not delete the PadstackInstance it resides on. Can you provide the code you are using so I can better understand of the behavior you are seeing? Thanks!

**Comment by svandenb-dev** [comment]
from @drewm102  You can ignore my comment, I was able to reproduce and am looking into a solution
