### ISSUE TITLE
BUG: Terminal.get_product_property_ids() failing

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#435]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I am not able to retrieve the product ids:

![image](https://github.com/user-attachments/assets/a4599362-0e7b-4e96-ba2b-b2c4cfd25e42)

![image](https://github.com/user-attachments/assets/306cedd8-0a83-486e-a327-f45260a6dd7b)

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
NA
```

**Comment by drewm102** [comment]
@svandenb-dev We throw an exception if the product properties are not defined for the specified ID. Is it expected for the product property to be empty in this case? If this behavior is not intuitive, we could also change it to just return an empty string rather than throw an assertion.

**Comment by svandenb-dev** [comment]
@drewm102 how can we get information on product properties ? I never quite understood how it works.

**Comment by svandenb-dev** [comment]
I see thanks. I will close this issue then.
