### ISSUE TITLE
How to assign Mesh operation ?

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#444]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

My mesh operation is created 
mop = GrpcLengthMeshOperation(name=name,
                                      net_layer_info=net_layer_op,
                                      refine_inside=refine_inside,
                                      mesh_region=mesh_region,
                                      max_length=max_length,
                                      restrict_max_length=restrict_length,
                                      restrict_max_elements=restrict_elements,
                                      max_elements=max_elements)

![image](https://github.com/user-attachments/assets/699f4272-3d79-405f-b6cc-8e0a6deca1b3)

![image](https://github.com/user-attachments/assets/31bbd45d-dc0f-4945-b582-578a897ddbc4)

![image](https://github.com/user-attachments/assets/19935dec-11a4-48f6-95a3-23d45096581b)

Mesh operation remains empty

![image](https://github.com/user-attachments/assets/2cb4a860-2f3a-4bfb-b50d-8180aea4cd76)

also tried this

![image](https://github.com/user-attachments/assets/8b4522d3-d77c-4e30-a23f-26596e665d94)

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
NA
```

**Comment by drewm102** [comment]
@svandenb-dev You are correct that mesh ops should be set like this:

```
self.mesh_operations = [mop]
```

However, `max_elements` should be a `str` not an `int`. Changing it to an `str` will fix this issue.

**Comment by svandenb-dev** [comment]
@drewm102 I confirm it is working now
