### ISSUE TITLE
Fail adding SparameterModel to ComponenentDef

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#452]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

```
n_port_model = GrpcSParameterModel.create(name=name, ref_net=reference_net)
n_port_model.reference_file = file_path
```
![image](https://github.com/user-attachments/assets/c14372c1-91ff-410f-b086-15abbdfe5798)
![image](https://github.com/user-attachments/assets/bfcdc8ef-e306-40d1-8249-9344a58c17e8)

self.component_def.add_component_model(n_port_model)

![image](https://github.com/user-attachments/assets/3541703f-ee7f-4149-9915-d9ec7bf123f7)

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
NA
```

**Comment by drewm102** [comment]
@svandenb-dev You should be using `NPortComponentModel` from the module `ansys.edb.core.definition.component_model`. `SParameterModel` objects are supposed to be set on `ComponentProperty` objects of `ComponentGroup` objects. Switching the object to a `NPortComponentModel` resolves the issue.
