### ISSUE TITLE
Layout.zone_primitives failing

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#467]
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### 🐞 Description of the bug

![Image](https://github.com/user-attachments/assets/85069488-09bf-4ae1-9e4a-d845cf32007b)

First I call this method we got this error

![Image](https://github.com/user-attachments/assets/5f49e0d0-60c7-4568-bd93-2769a273a2f2)

Then second time 
![Image](https://github.com/user-attachments/assets/f69191fe-2fad-42b8-8a22-3d4ff85d3d25)

But this test is supposed to have zone primitives

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

NA

**Comment by drewm102** [comment]
@svandenb-dev Based on the error message in the exception that is thrown, you need to synchronize the bend manager before retreiving the zone primitives. If you call `layout.synchronize_bend_manager()` before calling `layout.zone_primitives`, that should fix the issue.
